<?php
// module/Album/view/user/user/add.phtml:

$title = 'Delete user';
$this->headTitle($title);
?>
<div class="col-md-4 col-md-offset-4">
    <h1><?php echo $this->escapeHtml($title); ?></h1>

    <p>Are you sure that you want to delete user
        <strong><?php echo $this->escapeHtml($user->username); ?></strong>?
    </p>
    <?php
    $url = $this->url('user', array(
        'action' => 'delete',
        'id' => $this->id,
    ));
    ?>
    <form action="<?php echo $url; ?>" method="post">
        <div class="form-group">
            <input type="hidden" name="id" value="<?php echo (int)$user->id; ?>"/>
            <input type="submit" class="btn btn-primary" name="del" value="Yes"/>
            <input type="submit" class="btn btn-danger" name="del" value="No"/>
        </div>
    </form>
