<?php
// module/User/view/user/user/index.phtml:
$title = 'User Panel';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('user', array('action'=>'add'));?>" class="btn btn-default">Add new user</a>
</p>

<table class="table">
    <tr>
        <th>Username</th>
        <th>Email</th>
        <th>Full name</th>
        <th>Created at</th>
        <!-- <th>Người tạo</th> -->
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($user->username);?></td>
            <td><?php echo $this->escapeHtml($user->email);?></td>
            <td><?php echo $this->escapeHtml($user->full_name);?></td>
            <td><?php echo $this->escapeHtml($user->created_at);?></td>
            <!-- <td><?php // echo $this->escapeHtml($user->creator);?></td> -->
            <td>
                <a href="<?php echo $this->url('user',
                    array('action'=>'edit', 'id' => $user->id));?>" class="btn btn-primary">Edit</a>
                <a href="<?php echo $this->url('user',
                    array('action'=>'delete', 'id' => $user->id));?>" class="btn btn-danger">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>