<?php
// module/User/view/user/user/register.phtml:

$title = 'Register Account';
$this->headTitle($title);
?>
<?php
$form->setAttribute('action', $this->url('user', array('action' => 'register')));
$form->prepare();
?>
<div class="col-md-4 col-md-offset-4">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    ?>
    <div class="form-group">
        <label for="username">Username*</label>
        <?php echo $this->formRow($form->get('username')); ?>
    </div>
    <div class="form-group">
        <label for="email">Email*</label>
        <?php echo $this->formRow($form->get('email')); ?>
    </div>
    <div class="form-group">
        <label for="full_name">Full name</label>
        <?php echo $this->formRow($form->get('full_name')); ?>
    </div>
    <div class="form-group">
        <label for="password">Password*</label>
        <?php echo $this->formRow($form->get('password')); ?>
    </div>
    <div class="form-group">
        <label for="confirm_password">Confirm Password*</label>
        <?php echo $this->formRow($form->get('confirm_password')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formSubmit($form->get('submit')); ?>
        <a href="<?php echo $this->url('user', array('action' => 'index'));?>" class="btn btn-danger">Cancel</a>
    </div>
    <?php echo $this->form()->closeTag(); ?>
