<?php
// module/Album/view/album/album/add.phtml:

$title = 'Edit user information';
$this->headTitle($title);
?>
<?php
$form->setAttribute('action', $this->url('users', array('action' => 'edit', 'id' => $this->id)));
$form->prepare();
?>
<div class="col-md-4 col-md-offset-4">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <?php
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    ?>
    <div class="form-group">
        <label for="title">Username</label>
        <?php echo $this->formRow($form->get('username')); ?>
    </div>
    <div class="form-group">
        <label for="title">Email</label>
        <?php echo $this->formRow($form->get('email')); ?>
    </div>
    <div class="form-group">
        <label for="title">Full name</label>
        <?php echo $this->formRow($form->get('full_name')); ?>
    </div>
    <div class="form-group">
        <label for="title">Password</label>
        <?php echo $this->formRow($form->get('password')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formSubmit($form->get('submit')); ?>
        <a href="<?php echo $this->url('users', array('action' => 'index')); ?>" class="btn btn-danger">Cancel</a>
    </div>
    <?php echo $this->form()->closeTag(); ?>
