<?php
// module/Users/view/users/users/login.phtml:

$title = 'Login';
$this->headTitle($title);
?>
<?php
$form->setAttribute('action', $this->url('users', array('action' => 'authenticate')));
//$form->setAttribute('action', $this->url('users', array('action' => 'login')));
$form->prepare();
?>
<div class="row">
    <?php
    if ($this->messages) {
        foreach ($this->messages as $message) { ?>
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <?php echo $message; ?>
            </div>
        <?php }
    }
    ?>
</div>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <h1>
            <?php echo $this->escapeHtml($title); ?>
        </h1>
        <?php
        echo $this->form()->openTag($form);
        ?>
        <div class="form-group">
            <label for="username">Username*</label>
            <?php echo $this->formRow($form->get('username')); ?>
        </div>
        <div class="form-group">
            <label for="password">Password*</label>
            <?php echo $this->formRow($form->get('password')); ?>
        </div>
        <div class="checkbox">
            <label for="remember-me">Remember me</label>
            <?php echo $this->formCheckbox($form->get('remember_me')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formSubmit($form->get('submit')); ?>
            <a href="<?php echo $this->url('home'); ?>" class="btn btn-danger">Cancel</a>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
